export const DATABASE = 'DATABASE'
export const TABLE = 'TABLE'
export const PROCEDURE = 'PROCEDURE'
export const VIEW = 'VIEW'
export const PARENTCATALOG = 'PARENTCATALOG'
export const CATALOG = 'CATALOG'
