//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QWERTY.Shared.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QWERTY.Shared.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция выполнена не успешно.
        /// </summary>
        internal static string AddFlash_Операция_выполнена_не_успешно {
            get {
                return ResourceManager.GetString("AddFlash_Операция_выполнена_не_успешно", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция успешно выполнена.
        /// </summary>
        internal static string AddFlash_Операция_успешно_выполнена {
            get {
                return ResourceManager.GetString("AddFlash_Операция_успешно_выполнена", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось добавить пользователя в организацию.
        /// </summary>
        internal static string Не_удалось_добавить_пользователя_в_организацию {
            get {
                return ResourceManager.GetString("Не_удалось_добавить_пользователя_в_организацию", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось создать доступ в АС для пользователя.
        /// </summary>
        internal static string Не_удалось_создать_доступ_в_АС_для_пользователя {
            get {
                return ResourceManager.GetString("Не_удалось_создать_доступ_в_АС_для_пользователя", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объекты профиля не могут быть нулл.
        /// </summary>
        internal static string Объекты_профиля_не_могут_быть_нулл {
            get {
                return ResourceManager.GetString("Объекты_профиля_не_могут_быть_нулл", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не создан.
        /// </summary>
        internal static string Пользователь_не_создан {
            get {
                return ResourceManager.GetString("Пользователь_не_создан", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Право на объект не может быть нулл.
        /// </summary>
        internal static string Право_на_объект_не_может_быть_нулл {
            get {
                return ResourceManager.GetString("Право_на_объект_не_может_быть_нулл", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to табельный номер не может быть пустым.
        /// </summary>
        internal static string табельный_номер_не_может_быть_пустым {
            get {
                return ResourceManager.GetString("табельный_номер_не_может_быть_пустым", resourceCulture);
            }
        }
    }
}
